# Desafío - Manipulación y transformación de datos (Parte I)

a. carga de datos .pkl

In [ ]:
import pandas as pd

# Cargar los archivos .pkl y convertirlos en DataFrames
officers_df = pd.read_pickle('/content/officers.pkl')
incidents_df = pd.read_pickle('/content/incidents.pkl')
subjects_df = pd.read_pickle('/content/subjects.pkl')

# Mostrar las primeras filas de cada DataFrame para verificar
officers_df.head()

  case_number race gender  last_name first_name         full_name
0      44523A    L      M     Patino    Michael   Patino, Michael
1      44523A    W      M  Fillingim      Brian  Fillingim, Brian
2     121982X    L      M    Padilla    Gilbert  Padilla, Gilbert
3     605484T    W      M     Poston      Jerry     Poston, Jerry
4     384832T    B      M      Mondy    Michael    Mondy, Michael

In [ ]:
subjects_df.head()

  case_number race gender last_name first_name        full_name
0      44523A    L      M     Curry      James     Curry, James
1     121982X    L      M    Chavez    Gabriel  Chavez, Gabriel
2     605484T    L      M   Salinas       Nick    Salinas, Nick
3     384832T    B      M     Smith      James     Smith, James
4     384832T    B      M      Dews    Antonio    Dews, Antonio

In [ ]:
incidents_df.head()

,case_number,date,location,subject_statuses,subject_weapon,subjects,subject_count,officers,officer_count,grand_jury_disposition,attorney_general_forms_url,summary_url,summary_text,latitude,longitude
0,44523A,2013-02-23,3000 Chihuahua Street,Injured,Handgun,"Curry, James L/M",1,"Patino, Michael L/M; Fillingim, Brian W/M",2,No Bill,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Saturday, February 23, 2013, at approximate...",NaN,NaN
1,121982X,2010-05-03,1300 N. Munger Boulevard,Injured,Handgun,"Chavez, Gabriel L/M",1,"Padilla, Gilbert L/M",1,No Bill,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Monday, May 3, 2010, at approximately 8:06 ...",NaN,NaN
2,605484T,2007-08-12,200 S. Stemmons Freeway,Other,Shotgun,"Salinas, Nick L/M",1,"Poston, Jerry W/M",1,See Summary,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Sunday, August 12, 2007, at approximately 2...",NaN,NaN
3,384832T,2007-05-26,7900 S. Loop 12,Shoot and Miss,Unarmed,"Smith, James B/M; Dews, Antonio B/M; Spearman,...",3,"Mondy, Michael B/M",1,None,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Saturday, May 26, 2007, at approximately 1:...",NaN,NaN
4,244659R,2006-04-03,6512 South Loop 12,Injured,Hands,"Watkins, Caleb B/M",1,"Armstrong, Michael W/M",1,No Bill,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Monday, April 3, 2006, at approximately 11:...",NaN,NaN

b. Genera una tabla que contenga la unión de las 3 tablas. hint: utiliza sufijos para para las columnas que se llaman igual usando el parámetro suffixes de pd.merge().

In [ ]:
# Unir 'officers_df' con 'subjects_df' en base a la columna 'case_number'
officers_subjects_merged = pd.merge(officers_df, subjects_df, on='case_number', suffixes=('_officer', '_subject'))

# Unir el resultado con 'incidents_df' también en base a la columna 'case_number'
final_merged_df = pd.merge(officers_subjects_merged, incidents_df, on='case_number', suffixes=('_merged', '_incident'))

# Mostrar las primeras filas de la tabla unida
final_merged_df.head()

,case_number,race_officer,gender_officer,last_name_officer,first_name_officer,full_name_officer,race_subject,gender_subject,last_name_subject,first_name_subject,...,subjects,subject_count,officers,officer_count,grand_jury_disposition,attorney_general_forms_url,summary_url,summary_text,latitude,longitude
0,44523A,L,M,Patino,Michael,"Patino, Michael",L,M,Curry,James,...,"Curry, James L/M",1,"Patino, Michael L/M; Fillingim, Brian W/M",2,No Bill,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Saturday, February 23, 2013, at approximate...",NaN,NaN
1,44523A,W,M,Fillingim,Brian,"Fillingim, Brian",L,M,Curry,James,...,"Curry, James L/M",1,"Patino, Michael L/M; Fillingim, Brian W/M",2,No Bill,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Saturday, February 23, 2013, at approximate...",NaN,NaN
2,121982X,L,M,Padilla,Gilbert,"Padilla, Gilbert",L,M,Chavez,Gabriel,...,"Chavez, Gabriel L/M",1,"Padilla, Gilbert L/M",1,No Bill,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Monday, May 3, 2010, at approximately 8:06 ...",NaN,NaN
3,605484T,W,M,Poston,Jerry,"Poston, Jerry",L,M,Salinas,Nick,...,"Salinas, Nick L/M",1,"Poston, Jerry W/M",1,See Summary,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Sunday, August 12, 2007, at approximately 2...",NaN,NaN
4,384832T,B,M,Mondy,Michael,"Mondy, Michael",B,M,Smith,James,...,"Smith, James B/M; Dews, Antonio B/M; Spearman,...",3,"Mondy, Michael B/M",1,None,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Saturday, May 26, 2007, at approximately 1:...",NaN,NaN

c. Verifica si hay filas duplicadas; si es así, elimínalas.

In [ ]:
# Contar los valores en la columna 'gender_subject' y filtrar por el género 'F'
female_subjects_count = final_merged_df['gender_subject'].value_counts().get('F', 0)

# Mostrar el resultado
print(f'Número de sujetos de género F: {female_subjects_count}')

Número de sujetos de género F: 9

e. ¿En cuántos números de caso hay por lo menos una sospechosa que sea mujer? hint: utiliza el método unique() para obtener los valores únicos de una columna específica de un DataFrame luego de filtrar.

In [ ]:
# Filtrar los casos donde el género de los sujetos es 'F' (femenino)
female_subjects_cases = final_merged_df[final_merged_df['gender_subject'] == 'F']

# Obtener los valores únicos de 'case_number' en estos casos
unique_female_cases = female_subjects_cases['case_number'].unique()

# Contar el número de casos únicos
female_cases_count = len(unique_female_cases)

# Mostrar el resultado
print(f'Número de casos con al menos una sospechosa mujer: {female_cases_count}')

Número de casos con al menos una sospechosa mujer: 7

f. Genera una tabla pivote que muestre en las filas el género del oficial y en las columnas el género del subject. ¿Cómo interpretas los valores que muestra esta vista?

In [ ]:
# Crear una tabla pivote que cuente las ocurrencias de las combinaciones de género del oficial y del sujeto
pivot_table = pd.pivot_table(final_merged_df,
                             index='gender_officer',
                             columns='gender_subject',
                             aggfunc='size',
                             fill_value=0)

# Mostrar la tabla pivote
pivot_table

gender_subject  F    M
gender_officer
F               2   18
M               7  350

Los valores en la tabla pivot anterior representan el número de incidentes en los que un oficial de un género específico interactuó con un sujeto de otro género

# 2. Para continuar con el desarrollo de este desafío, necesitarás el archivos Cleaned_DS_Jobs.csv

a. Carga los datos y crea un DataFrame con ellos

In [ ]:
cleaned_ds_jobs_df = pd.read_csv('/content/Cleaned_DS_Jobs.csv')

# Mostrar las primeras filas del DataFrame para verificar
cleaned_ds_jobs_df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Type of ownership,Industry,...,company_age,python,excel,hadoop,spark,aws,tableau,big_data,job_simp,seniority
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,Nonprofit Organization,Insurance Carriers,...,27,0,0,0,0,1,0,0,data scientist,senior
1,Data Scientist,137-171,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,Company - Public,Research & Development,...,52,0,0,1,0,0,0,1,data scientist,na
2,Data Scientist,137-171,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,Private Practice / Firm,Consulting,...,39,1,1,0,0,1,0,0,data scientist,na
3,Data Scientist,137-171,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,Company - Public,Electrical & Electronic Manufacturing,...,20,1,1,0,0,1,0,0,data scientist,na
4,Data Scientist,137-171,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,Company - Private,Advertising & Marketing,...,22,1,1,0,0,0,0,0,data scientist,na

b. Utiliza la siguiente lista de valores que serán considerados como nulos: ["na", "NA", -1, "0", "-1", "null", "n/a", "N/A", "NULL"] (hint: utiliza el método replace para reemplazar los valores indicados por np.nan)

In [ ]:
import numpy as np

# Lista de valores a considerar como nulos
valores_nulos = ["na", "NA", -1, "0", "-1", "null", "n/a", "N/A", "NULL"]

# Reemplazar los valores indicados por pd.NA
cleaned_ds_jobs_df.replace(valores_nulos, pd.NA, inplace=True)

# Mostrar las primeras filas del DataFrame para verificar el cambio
print("DataFrame después de reemplazar valores nulos:")
cleaned_ds_jobs_df.head()

DataFrame después de reemplazar valores nulos:

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Type of ownership,Industry,...,company_age,python,excel,hadoop,spark,aws,tableau,big_data,job_simp,seniority
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,Nonprofit Organization,Insurance Carriers,...,27,0,0,0,0,1,0,0,data scientist,senior
1,Data Scientist,137-171,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,Company - Public,Research & Development,...,52,0,0,1,0,0,0,1,data scientist,<NA>
2,Data Scientist,137-171,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,Private Practice / Firm,Consulting,...,39,1,1,0,0,1,0,0,data scientist,<NA>
3,Data Scientist,137-171,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,Company - Public,Electrical & Electronic Manufacturing,...,20,1,1,0,0,1,0,0,data scientist,<NA>
4,Data Scientist,137-171,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,Company - Private,Advertising & Marketing,...,22,1,1,0,0,0,0,0,data scientist,<NA>

c. Elimina todas las filas con datos faltantes. (hint: utiliza el método .dropna())

In [ ]:
# Eliminar todas las filas con datos faltantes
cleaned_ds_jobs_df.dropna(inplace=True)

# Mostrar las primeras filas del DataFrame después de eliminar filas con datos faltantes
cleaned_ds_jobs_df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Type of ownership,Industry,...,company_age,python,excel,hadoop,spark,aws,tableau,big_data,job_simp,seniority
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,Nonprofit Organization,Insurance Carriers,...,27,0,0,0,0,1,0,0,data scientist,senior
32,Senior Research Statistician- Data Scientist,75-131,Acuity is seeking a Senior Research Statistici...,4.8,Acuity Insurance,"Sheboygan, WI","Sheboygan, WI",1001 to 5000 employees,Company - Private,Insurance Carriers,...,95,0,0,0,0,0,0,0,data scientist,senior
38,Senior Analyst/Data Scientist,75-131,At Edmunds were driven to make car buying easi...,3.4,Edmunds.com,"Santa Monica, CA","Santa Monica, CA",501 to 1000 employees,Company - Private,Internet,...,54,1,1,0,0,1,1,0,data scientist,senior
45,Senior Data Scientist,75-131,Klaviyo is looking for Senior Data Scientists ...,4.8,Klaviyo,"Boston, MA","Boston, MA",201 to 500 employees,Company - Private,Computer Hardware & Software,...,8,0,0,0,0,0,0,0,data scientist,senior
54,Senior Data Scientist,75-131,Benson Hill empowers innovators to develop mor...,3.5,Benson Hill,"Saint Louis, MO","Saint Louis, MO",201 to 500 employees,Company - Private,Biotech & Pharmaceuticals,...,8,1,1,0,0,0,0,1,data scientist,senior

d. A partir de la columna “Salary Estimate”, genera dos columnas: Salario Estimado Mínimo y Máximo. (hint: Utiliza el método apply sobre la columna.)

In [ ]:
# Función para separar el salario mínimo y máximo
def split_salary(salary):
    min_salary, max_salary = salary.split('-')  # Separar por el guion
    return pd.Series([int(min_salary), int(max_salary)])  # Retornar como dos columnas

# Aplicar la función y crear las columnas de salario mínimo y máximo
cleaned_ds_jobs_df[['Salario Mínimo', 'Salario Máximo']] = cleaned_ds_jobs_df['Salary Estimate'].apply(split_salary)

# Mostrar el DataFrame resultante
cleaned_ds_jobs_df

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Type of ownership,Industry,...,excel,hadoop,spark,aws,tableau,big_data,job_simp,seniority,Salario Mínimo,Salario Máximo
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,Nonprofit Organization,Insurance Carriers,...,0,0,0,1,0,0,data scientist,senior,137,171
32,Senior Research Statistician- Data Scientist,75-131,Acuity is seeking a Senior Research Statistici...,4.8,Acuity Insurance,"Sheboygan, WI","Sheboygan, WI",1001 to 5000 employees,Company - Private,Insurance Carriers,...,0,0,0,0,0,0,data scientist,senior,75,131
38,Senior Analyst/Data Scientist,75-131,At Edmunds were driven to make car buying easi...,3.4,Edmunds.com,"Santa Monica, CA","Santa Monica, CA",501 to 1000 employees,Company - Private,Internet,...,1,0,0,1,1,0,data scientist,senior,75,131
45,Senior Data Scientist,75-131,Klaviyo is looking for Senior Data Scientists ...,4.8,Klaviyo,"Boston, MA","Boston, MA",201 to 500 employees,Company - Private,Computer Hardware & Software,...,0,0,0,0,0,0,data scientist,senior,75,131
54,Senior Data Scientist,75-131,Benson Hill empowers innovators to develop mor...,3.5,Benson Hill,"Saint Louis, MO","Saint Louis, MO",201 to 500 employees,Company - Private,Biotech & Pharmaceuticals,...,1,0,0,0,0,1,data scientist,senior,75,131
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
579,Senior Data Engineer,138-158,Senior Data Engineer\n\nMaster’s degree in Inf...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,Company - Private,Advertising & Marketing,...,0,1,1,0,1,0,data engineer,senior,138,158
583,Senior Data Scientist,80-132,Job Requisition ID #\n20WD40666\nJob Title\nSe...,4.0,Autodesk,"San Francisco, CA","San Rafael, CA",5001 to 10000 employees,Company - Public,Computer Hardware & Software,...,0,1,1,0,0,1,data scientist,senior,80,132
601,Senior Data Scientist,87-141,"Secure our Nation, Ignite your Future\n\nJob S...",4.2,ManTech,"Alexandria, VA","Herndon, VA",5001 to 10000 employees,Company - Public,Research & Development,...,0,1,1,0,1,1,data scientist,senior,87,141
640,Senior Data Scientist,105-167,"About Us\n\nAt GutCheck, we pioneered agile ma...",3.8,GutCheck,"Denver, CO","Denver, CO",51 to 200 employees,Company - Private,Advertising & Marketing,...,0,0,0,0,0,0,data scientist,senior,105,167
641,Sr. ML/Data Scientist - AI/NLP/Chatbot,105-167,Sr. ML/Data Scientist - AI/NLP/Chatbot\n\nMist...,3.8,Juniper Networks,"Cupertino, CA","Sunnyvale, CA",5001 to 10000 employees,Company - Public,Telecommunications Services,...,1,0,1,1,0,0,data scientist,senior,105,167

e. Realiza la recodificación de la columna Size con los valores de la siguiente tabla: (hint: utilice reemplazo con diccionario usando el método replace sobre la columna.)

In [ ]:
recodificacion_size = {
    '10000+ employees': 'Mega Empresas',
    '5001 to 10000 employees': 'Grandes Empresas',
    '1001 to 5000 employees': 'Medianas Empresas',
    '201 to 500 employees': 'Pequeñas Empresas',
    '51 to 200 employees': 'Pequeñas Grandes Empresas',
    '501 to 1000 employees': 'Microempresas',
    'Unknown': 'Empresas sin Información'
}

# Crear la nueva columna "descripcion" usando el diccionario
cleaned_ds_jobs_df['descripcion'] = cleaned_ds_jobs_df['Size'].replace(recodificacion_size)

# Mostrar las primeras filas del DataFrame para verificar el cambio
print("DataFrame después de agregar la columna 'descripcion':")
cleaned_ds_jobs_df

DataFrame después de agregar la columna 'descripcion':

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Type of ownership,Industry,...,hadoop,spark,aws,tableau,big_data,job_simp,seniority,Salario Mínimo,Salario Máximo,descripcion
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,Nonprofit Organization,Insurance Carriers,...,0,0,1,0,0,data scientist,senior,137,171,Medianas Empresas
32,Senior Research Statistician- Data Scientist,75-131,Acuity is seeking a Senior Research Statistici...,4.8,Acuity Insurance,"Sheboygan, WI","Sheboygan, WI",1001 to 5000 employees,Company - Private,Insurance Carriers,...,0,0,0,0,0,data scientist,senior,75,131,Medianas Empresas
38,Senior Analyst/Data Scientist,75-131,At Edmunds were driven to make car buying easi...,3.4,Edmunds.com,"Santa Monica, CA","Santa Monica, CA",501 to 1000 employees,Company - Private,Internet,...,0,0,1,1,0,data scientist,senior,75,131,Microempresas
45,Senior Data Scientist,75-131,Klaviyo is looking for Senior Data Scientists ...,4.8,Klaviyo,"Boston, MA","Boston, MA",201 to 500 employees,Company - Private,Computer Hardware & Software,...,0,0,0,0,0,data scientist,senior,75,131,Pequeñas Empresas
54,Senior Data Scientist,75-131,Benson Hill empowers innovators to develop mor...,3.5,Benson Hill,"Saint Louis, MO","Saint Louis, MO",201 to 500 employees,Company - Private,Biotech & Pharmaceuticals,...,0,0,0,0,1,data scientist,senior,75,131,Pequeñas Empresas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
579,Senior Data Engineer,138-158,Senior Data Engineer\n\nMaster’s degree in Inf...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,Company - Private,Advertising & Marketing,...,1,1,0,1,0,data engineer,senior,138,158,Pequeñas Grandes Empresas
583,Senior Data Scientist,80-132,Job Requisition ID #\n20WD40666\nJob Title\nSe...,4.0,Autodesk,"San Francisco, CA","San Rafael, CA",5001 to 10000 employees,Company - Public,Computer Hardware & Software,...,1,1,0,0,1,data scientist,senior,80,132,Grandes Empresas
601,Senior Data Scientist,87-141,"Secure our Nation, Ignite your Future\n\nJob S...",4.2,ManTech,"Alexandria, VA","Herndon, VA",5001 to 10000 employees,Company - Public,Research & Development,...,1,1,0,1,1,data scientist,senior,87,141,Grandes Empresas
640,Senior Data Scientist,105-167,"About Us\n\nAt GutCheck, we pioneered agile ma...",3.8,GutCheck,"Denver, CO","Denver, CO",51 to 200 employees,Company - Private,Advertising & Marketing,...,0,0,0,0,0,data scientist,senior,105,167,Pequeñas Grandes Empresas
641,Sr. ML/Data Scientist - AI/NLP/Chatbot,105-167,Sr. ML/Data Scientist - AI/NLP/Chatbot\n\nMist...,3.8,Juniper Networks,"Cupertino, CA","Sunnyvale, CA",5001 to 10000 employees,Company - Public,Telecommunications Services,...,0,1,1,0,0,data scientist,senior,105,167,Grandes Empresas

f. Genera una tabla pivote que muestre la media del salario estimado mínimo y la media del salario estimado máximo por tamaño de empresa. (hint: utiliza pd.pivot_table para generar la vista adecuada con las columnas generadas.)

In [ ]:
# Generar la tabla pivote
tabla_pivote = pd.pivot_table(
    cleaned_ds_jobs_df,
    values=['Salario Mínimo', 'Salario Máximo'],  # Columnas a promediar
    index='descripcion',  # Agrupar por tamaño de empresa
    aggfunc='mean'  # Calcular la media
)

# Mostrar la tabla pivote
print("Tabla pivote de la media del salario estimado mínimo y máximo por tamaño de empresa:")
tabla_pivote

Tabla pivote de la media del salario estimado mínimo y máximo por tamaño de empresa:

                           Salario Máximo  Salario Mínimo
descripcion
Empresas sin Información       110.500000       73.000000
Grandes Empresas               138.875000       92.125000
Medianas Empresas              137.461538       93.923077
Mega Empresas                  151.111111       97.888889
Microempresas                  146.235294      100.176471
Pequeñas Empresas              141.142857       93.571429
Pequeñas Grandes Empresas      137.666667      100.666667